process ASSIGN {
    /*
     * This function takes the annotation table generated by viral_contig_maps.py and generates a table that
     * provides the taxonomic lineage of each viral contig, based on the corresponding ViPhOG annotations
    */

    tag "${meta.id}"
    label 'process_single'

    container 'quay.io/microbiome-informatics/virify-python3:1.1'

    input:
    tuple val(meta), path(tab)
    path db
    path factor

    output:
    tuple val(meta), path("*_taxonomy.tsv"),        emit: taxonomy_tsv

    script:
    def args   = task.ext.args ?: ''
    def factor_file = factor ? "--factor ${factor}": ""
    """
    contig_taxonomic_assign.py \
       -i ${tab} \
       -d ${db} \
       ${factor_file} \
       ${args}
    """
}
